### ISSUE TITLE
Data with no 'date' crashes compile release transform

### ISSUE THREAD

**Issue by odscjames** [open-contracting/kingfisher-process#147]
As reported in https://github.com/open-contracting/ocds-merge/issues/21

The data is in digiwhist Croatia, and is

```


{
  "uri": "https:\/\/localhost:4567\/protected\/master_tender\/id\/00011445-02da-4e03-a9fc-c9322ce787e3?format=ocds",
  "version": "1.1",
  "publisher": {
    "name": "digiwhist"
  },
  "extensions": [
    "https:\/\/raw.githubusercontent.com\/open-contracting\/ocds_lots_extension\/v1.1.1\/extension.json",
    "https:\/\/raw.githubusercontent.com\/open-contracting\/ocds_bid_extension\/v1.1.1\/extension.json",
    "https:\/\/raw.githubusercontent.com\/open-contracting\/ocds_requirements_extension\/master\/extension.json"
  ],
  "releases": [
    {
      "ocid": "ocds-7bcrc6-00011445-02da-4e03-a9fc-c9322ce787e3",
      "id": "00011445-02da-4e03-a9fc-c9322ce787e3",
      "initiationType": "tender",
      "buyer": {
        "id": "32f4315d-c727-4e14-90c5-f088771cb5dc",
        "name": "KONCERTNA DVORANA VATROSLAVA LISINSKOG"
      },
      "parties": [
        {
          "id": "32f4315d-c727-4e14-90c5-f088771cb5dc",
          "name": "KONCERTNA DVORANA VATROSLAVA LISINSKOG",
          "additionalIdentifiers": [
            {
              "id": "54493774760",
              "scheme": "ORGANIZATION_ID"
            }
          ],
          "address": {
            "streetAddress": "Trg S. Radi\u00c4\u2021a 4",
            "postalCode": "10000",
            "countryName": "Hrvatska"
          },
          "contactPoint": {
            "name": "Anita Toki\u00c4\u2021",
            "email": "anita.tokic@lisinski.hr",
            "url": "http:\/\/www.lisinski.hr",
            "telephone": "+385 16121154"
          },
          "roles": [
            "buyer"
          ]
        }
      ],
      "tender": {
        "documents": [
          {
            "id": "document-2",
            "url": "https:\/\/eojn.nn.hr\/SPIN\/APPLICATION\/IPN\/DocumentManagement\/DokumentPodaciFrm.aspx?id=346021",
            "documentType": "tenderNotice"
          }
        ],
        "id": "2013\/S 002-0054865",
        "title": "Izrada i monta\u017ea zvukoizolacijskih vrata za veliku dvoranu Koncertne dvorane Vatroslava lisinskog",
        "description": "nabava roba i usluga",
        "value": {
          "amount": 115500,
          "currency": "HRK"
        },
        "procurementMethod": "open",
        "procurementMethodDetails": "Otvoreni",
        "mainProcurementCategory": "goods",
        "awardCriteria": "priceOnly",
        "awardCriteriaDetails": "PRICE: 100",
        "tenderPeriod": {
          "endDate": "2013-07-09T12:00:00.000Z"
        },
        "items": [
          {
            "id": "item-1",
            "classification": {
              "id": "45421100-5",
              "scheme": "CPV"
            }
          }
        ],
        "lots": [
          {
            "id": "lot-1"
          }
        ]
      },
      "bids": {
        
      },
      "tag": [
        "compiled"
      ]
    }
  ],
  "publishedDate": "2019-03-06T12:09:16.475Z"
}


```

This causes crashes. It also causes problems in that further work on the transform for that collection only will NOT BE DONE (but other transforms will be done).

I guess we should check for a missing date key specifically, log that error somewhere and then carry on with the rest of that collection's transform?

Maybe the error could be logged in a collection_file_item row?

**Comment by jpmckinney** [comment]
That looks like a release package containing a single compiled release (because `tag` is `["compiled"]`). 

Are you using the HEAD version of ocds-merge? This should no longer error, because OCDS Merge now has a special case to skip sorting on `date` if only one release is submitted.

If we end up having multiple compiled releases with the same `ocid`, Kingfisher can check whether `tag` is `["compiled"]` and if so, simply pass the compiled release through instead of re-compiling it.

**Comment by odscjames** [comment]
Those points apply in this specific case. (We are using a locked release of ocdsmerge, so the first thing to do would be upgrade that.)

But the basic problem here is that a crash while processing this transform means A) the rest of the transform won't get processed and B) the knowledge of the crash is not logged anywhere it is relatively easy for analysts to check out and report on.

So in general we should look at this, as we don't know what bad data we might get in the future. This ticket is to note this for the future and hasn't yet been given a priority.

I personally would look at this before trying to fix this particular piece of data so a general fix is in place for other cases to.

**Comment by jpmckinney** [comment]
For the purpose of solving the immediate analyst issue (which I assumed this issue was about given the subject "Data with no 'date' crashes compile release transform" and the specific example), let's pursue the OCDS Merge upgrade.

We can create a new issue for handing exceptions raised during transformation. In terms of priority and sequence, it might be that the solution next time, like this time, will be to fix the dependency, rather than make transforms more robust.

**Comment by robredpath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data with no 'date' crashes compile release transform #147](https://trello.com/c/klvZiQ4O/28-data-with-no-date-crashes-compile-release-transform-147)

**Comment by robredpath** [comment]
@odscjames Did we get anywhere with this? I've added a Trello card for the specific reported issue of a crash under certain circumstances with the Digiwhist Croatia scraper. Please can you add a new GitHub issue for the more general solution (which it's great that you've started to think about!) and add a Trello card to the I&R pool if you feel it's important to work on that in the relatively near future.

**Comment by odscjames** [comment]
For the specific case, Process is currently using 0.5.2 ocdsmerge so the fix mentioned is included.

I've just tried running the transform in collection 289 by hand -  and locally with the latest data (this one is ~100,000 lines so not to long). We are still seeing the crash - it is now a ocdsmerge.merge.MissingDateKeyError crash.

I don't think that we have discussed how to handle this specific case, and that's a question for the analysts really. Should we look for records with no date and just silently drop them? Should we not merge anything for that OCID if a single release has no date?

Depending on the answer, we also need to discuss whether the fix should happen here or in ocdsmerge.

I will make a new card for logging Python crashes while running a Transform.

**Comment by robredpath** [comment]
@duncandewhurst @pindec ^^

**Comment by jpmckinney** [comment]
> That looks like a release package containing a single compiled release (because `tag` is `["compiled"]`). 

> …

> If we end up having multiple compiled releases with the same `ocid`, Kingfisher can check whether `tag` is `["compiled"]` and if so, simply pass the compiled release through instead of re-compiling it.

I ran the following on collection 288:

```sql
SELECT DISTINCT(data.data->'tag')
FROM release_with_collection
INNER JOIN data ON data.id = data_id
WHERE data.data->'date' IS NULL AND collection_id = 288;
```

Result: `["compiled"]`

In Digiwhist Georgia's case, there are somehow compiled releases in the release table. The solution is either:

1. Exclude compiled releases (releases with a `tag` of `["compiled"]`), and compile releases with the remaining releases. This is not robust, because it's possible that the compiled release is the only release in the dataset for that OCID.
2. Before compiling releases, pass through any already compiled releases, and remove any non-compiled releases with the same OCID as those that were passed through before doing compilation. If there are two compiled releases to pass through with the same OCID, error.

**Comment by jpmckinney** [comment]
I don't think this should be solved in ocds-merge, because it should be up to the user to decide whether to (a) pass-through a compiled release or (b) re-compile a compiled release using individual releases (assuming they are available, which perhaps the user knows in advance). For Kingfisher, (a) is the more robust option. It'd be good to add a collection note when this occurs.

**Comment by duncandewhurst** [comment]
That approach sounds good to me.

One of the first steps in the template data feedback colab notebook is to look at the un-compiled collection and count the releases by tag, so we would likely spot that there was something odd going on anyway, but the collection note is a good idea too.

Once we have been tipped off,  we can fairly easily go back to the un-compiled collection, extract any individual releases with the same ocids as the compiled releases in that collection, compile them using ocds-merge and then compare the results to the compiled releases to see if any information was lost.

**Comment by odscjames** [comment]
Unfortunately, this spec does not solve the problem with digiwhist Croatia.

This data has one place where a complied release is repeated, and thus under the spec "If there are two compiled releases to pass through with the same OCID, error" it crashes. 

The data is OCID ocds-7bcrc6-01aa2eed-d893-4a74-8aeb-43f1f0737bce and as far as I can tell, the two lines are exactly the same except one has "publishedDate": "2019-03-06T12:09:55.662Z" and the other has "publishedDate": "2019-03-06T12:09:55.974Z".

What to do in this case? We could just pass through one at random, and make a note saying we have done that?

**Comment by jpmckinney** [comment]
Since it's a rare case that I don't suspect will be encountered again, we can take the first one encountered, and then make a note on the collection about any/each later compiled release, with the id's to make it easy for analysts to select the relevant rows.

**Comment by odscjames** [comment]
Done - I will leave this running overnight on real data to check the results, and check up on this later.

I would however like to look at storing this not in a collection note. Collection notes aren't really meant for this, and notes are only linked to a collection and nothing else. That makes it hard to query against well, and also notes from an actual human may be lost among the noise (the current run is generating a lot of automatic notes!)

Instead, each compiled release has a collection_file_item row, and that table has a warnings column, that stores a list of strings in a JSON type. This is exactly what this is meant for, so I'd prefer to store it there.

**Comment by jpmckinney** [comment]
Makes sense to me to use warnings then!

**Comment by odscjames** [comment]
Live
